# Generated by Django 6.0.3 on 2026-03-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionlisting_bid_comment_delete_actionlisting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="watchlist",
        ),
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="users_watchlist", to="auctions.auctionlisting"
            ),
        ),
    ]
