# Generated by Django 6.0.3 on 2026-03-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_remove_auctionlisting_watchlist_user_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="current_highest_bid",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
