# Generated by Django 6.0.3 on 2026-03-31 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_auctionlisting_current_highest_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="current_price",
        ),
        migrations.AddField(
            model_name="bid",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
