# Generated by Django 6.0.3 on 2026-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_remove_auctionlisting_current_price_bid_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="current_highest_bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
