# Generated by Django 6.0.3 on 2026-04-01 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_bid_amount_alter_comment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.auctionlisting",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
